# Reference:https://github.com/marketplace/actions/build-and-push-docker-images
name: Space Xplorer Server docker image build

on:
  push:
    branches: [ main, beta, develop ]

jobs:
  build_application:
    name: Build server bundle
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Application
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm install
      - run: npm run build

      - name: Upload build artifact
        continue-on-error: false
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/server.js

  push_to_registries:
    name: Pushes Docker image to Dockerhub and Github Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wyvarn/space-xplorer-server
          dockerfile: "Dockerfile"
          tag_with_ref: true

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: wyvarn/space-xplorer-client/space-xplorer-server
          dockerfile: "Dockerfile"
          tag_with_ref: true